### ISSUE TITLE
How to fix puppeter error not found libX11-xcb.so.1

### ISSUE THREAD

**Issue by alvarojmp** [alvarojmp/aj-bank#1]
For resolve this issue in Ubuntu when use puppeteer module , install theses dependencies:

`sudo apt install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget`

**source**: [https://techoverflow.net/2018/06/05/how-to-fix-puppetteer-error-while-loading-shared-libraries-libx11-xcb-so-1-cannot-open-shared-object-file-no-such-file-or-directory/](url)

**Comment by alvaro-jmp** [comment]
And more info => https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
# https://techoverflow.net/2018/06/05/
